import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider, GoogleOneTap } from "@clerk/nextjs";
import { Inter,Outfit } from "next/font/google";

const inter = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Course Generator AI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
      <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
